name: "ernet"
network: "ernet"
#* Output Settings
output_dir: './logs/${config.name}'  # checkpoint_latest save path
save_suffix: '.mhd'  # the file format saved when training
#* Model Settings
in_classes: 1
out_classes: 2
load_mode: 0  # 0: load nothing 1: load from checkpoint 2: load from pre_trained model(supervised)
# seg 可用
# ckpt: '/disk/cc/FM-MLP/logs/unet/2024-01-04/unet'
# extractor_ckpt: '/disk/cc/FM-MLP/logs/extractor/2024-01-05/19-27-17'
ckpt: '/disk/cc/FM-MLP/logs/compare/vessel/ernet/2024-01-14/13-48-18'
extractor_ckpt: ''
latest_checkpoint_file: 'latest_checkpoint.pt'  # ckpt + latest_checkpoint_file determined load which ckpt file
#* Training Settings
patch_size: 64, 64, 64  # if 2D: 128,128,1
# unetr
