name: "semi_extractor"
network: "unet"
#* Output Settings
output_dir: './logs/${config.name}'  # checkpoint_latest save path
save_suffix: '.mhd'  # the file format saved when training
#* Model Settings
used_label: 1-12 # "1-5":第一个数据到第五个数据  [2,3,5,6,7] 第2 3 5 6 7个数据被采用
# used_label: "1-7" # "1-5":第一个数据到第五个数据  [2,3,5,6,7] 第2 3 5 6 7个数据被采用
in_classes: 1
out_classes: 1
load_mode: 0  # 0: load nothing 1: load from checkpoint 2: load from pre_trained model(supervised)
# seg 可用
# ckpt: '/disk/cc/FM-MLP/logs/unet/2024-01-04/unet'
# extractor_ckpt: '/disk/cc/FM-MLP/logs/semi/vessel/new_extractor_source/2024-01-11/00-44-45'
ckpt: '/disk/cc/FM-MLP/logs/semi/zhougu/our/2024-01-14/23-19-13'
latest_checkpoint_file: 'latest_checkpoint.pt'  # ckpt + latest_checkpoint_file determined load which ckpt file
#* Training Settings
crop_or_pad_size: 64, 64, 64  # if 2D: 256,256,1  #USELESS
patch_size: 64, 64, 64  # if 2D: 128,128,1
swap_size: 30,30,10
swap_iterations: 10